<?php if(!defined('s7V9pz')) {die();}?><?php
function grpost($id = 0, $code = 0) {
    $r[0] = false;
    if (!empty($id) && !empty($code)) {
        $rs = db('Grupo', 's', 'mails', 'id,code', $id, $code);
        if (isset($rs[0]['id'])) {
            $r[0] = true;
            $emtitle = 'email_'.$rs[0]['type'].'_title';
            $emdesc = 'email_'.$rs[0]['type'].'_desc';
            $embtn = 'email_'.$rs[0]['type'].'_btn';
            $mail['title'] = $GLOBALS["lang"]->$emtitle;
            $mail['desc'] = $GLOBALS["lang"]->$emdesc;
            $mail['btn'] = $GLOBALS["lang"]->$embtn;
            $mail['link'] = $GLOBALS["core"]->url.'mail/do/'.$id.'/'. $code.'/';
            $mail['sitename'] = $GLOBALS["default"]->sendername;
            $mail['footer'] = $GLOBALS["lang"]->email_footer;
            $mail['complimentary'] = $GLOBALS["lang"]->email_complimentary_close;
            $mail['copylink'] = $GLOBALS["lang"]->email_copy_link;
            $r[1] = '<div><div id=":nr" class="ii gt">';
            $r[1] .= '<div id=":ns" class="a3s aXjCH adM"><div class="HOEnZb"><div class="im">';
            $r[1] .= '<div bgcolor="#fafbfc" style="Margin:0;padding:0">';
            $r[1] .= '<table border="0" cellpadding="0" cellspacing="0" width="100%">';
            $r[1] .= '<tbody><tr>';
            $r[1] .= '<td style="background-color:#fafbfc">';
            $r[1] .= '<center bgcolor="#fafbfc" style="width:100%;background-color:#fafbfc">';
            $r[1] .= '<div style="max-width:620px;font-size:0;margin:0 auto">';
            $r[1] .= '<div style="font-size:1px;line-height:1px;display:none!important">';
            $r[1] .= '</div><table border="0" cellpadding="0" cellspacing="0" style="width:100%">';
            $r[1] .= '<tbody><tr><td><table border="0" cellpadding="0" cellspacing="0" style="width:100%">';
            $r[1] .= '<tbody><tr>';
            $r[1] .= '<td align="center" style="padding-bottom:20px">';
            $r[1] .= '<table border="0" cellpadding="0" cellspacing="0" style="font-family:'."'Open+Sans','Open Sans'".',Helvetica,Arial,sans-serif;font-size:13px;line-height:18px;color:#00c0ea;text-align:center;width:152px">';
            $r[1] .= '<tbody>';
            $r[1] .= '<tr>';
            $r[1] .= '<td style="padding:20px 0 10px 0">';
            $r[1] .= '<a href="#" style="text-decoration:none"><img alt="'.htmlspecialchars_decode($mail['sitename']).'" border="0" height="auto" src="'.htmlspecialchars_decode(mf("grupo/global/emaillogo.png")).'" style="display:block;width:100px!important;font-family:'."'Open+Sans','Open Sans'".',Helvetica,Arial,sans-serif;font-size:22px;line-height:26px;color:#000000;text-transform:uppercase;text-align:center;letter-spacing:1px" width="152" class="CToWUd"></a>';
            $r[1] .= '</td></tr></tbody></table></td></tr></tbody></table></td></tr><tr><td>';
            $r[1] .= '<table border="0" cellpadding="0" cellspacing="0" style="width:100%">';
            $r[1] .= '<tbody><tr>';
            $r[1] .= '<td bgcolor="#fafbfc" style="width:7px;font-size:1px">&nbsp;</td>';
            $r[1] .= '<td bgcolor="#f5f6f7" style="width:1px;font-size:1px">&nbsp;</td>';
            $r[1] .= '<td bgcolor="#f0f2f3" style="width:1px;font-size:1px">&nbsp;</td>';
            $r[1] .= '<td bgcolor="#edeef1" style="width:1px;font-size:1px">&nbsp;</td>';
            $r[1] .= '<td bgcolor="#ffffff">';
            $r[1] .= '<table border="0" cellpadding="0" cellspacing="0" style="width:100%">';
            $r[1] .= '<tbody><tr>';
            $r[1] .= '<td style="text-align:center;padding:40px 40px 40px 40px;border-top:3px solid #02b3e4">';
            $r[1] .= '<div style="display:inline-block;width:100%;max-width:520px">';
            $r[1] .= '<table border="0" cellpadding="0" cellspacing="0" style="font-family:'."'Open+Sans','Open Sans'".',Helvetica,Arial,sans-serif;font-size:14px;line-height:24px;color:#525c65;text-align:left;width:100%">';
            $r[1] .= '<tbody><tr><td>';
            $r[1] .= '<p style="Margin:0;font-size:18px;line-height:23px;color:#102231;font-weight:bold">';
            $r[1] .= '<strong>';
            $r[1] .= htmlspecialchars_decode($mail['title']).'</strong><br><br>';
            $r[1] .= '</p></td></tr><tr><td>';
            $r[1] .= htmlspecialchars_decode($mail['desc']).'<br><br>';
            $r[1] .= '</td></tr><tr>';
            $r[1] .= '<td align="center" style="padding:15px 0 40px 0;border-bottom:1px solid #f3f6f9">';
            $r[1] .= '<table border="0" cellpadding="0" cellspacing="0" style="border-collapse:separate!important;border-radius:15px;width:230px">';
            $r[1] .= '<tbody><tr>';
            $r[1] .= '<td align="center" valign="top">';
            $r[1] .= '<a href="'.htmlspecialchars_decode($mail['link']).'" style="background-color:#01b3e3;border-collapse:separate!important;border-top:10px solid #01b3e3;border-bottom:10px solid #01b3e3;border-right:45px solid #01b3e3;border-left:45px solid #01b3e3;border-radius:4px;color:#ffffff;display:inline-block;font-family:'."'Open+Sans','Open Sans'".',Helvetica,Arial,sans-serif;font-size:13px;font-weight:bold;text-align:center;text-decoration:none;letter-spacing:2px;text-transform:uppercase" target="_blank">'.htmlspecialchars_decode($mail['btn']).'</a>';
            $r[1] .= '</td></tr></tbody></table></td></tr><tr>';
            $r[1] .= '<td style="padding-top:30px">';
            $r[1] .= '<p style="margin:20px 0 20px 0;">';
            $r[1] .= htmlspecialchars_decode($mail['copylink']);
            $r[1] .= '</p>';
            $r[1] .= '<p style="Margin:20px 0;font-size:12px;line-height:17px;word-wrap:break-word;word-break:break-all">';
            $r[1] .= '<a href="'.htmlspecialchars_decode($mail['link']).'" style="color:#5885ff;text-decoration:underline" target="_blank">'.htmlspecialchars_decode($mail['link']).'</a>';
            $r[1] .= '</p></td></tr><tr><td style="font:14px/16px Arial,Helvetica,sans-serif;color:#363636;padding:0 0 14px">';
            $r[1] .= htmlspecialchars_decode($mail['complimentary']).'</td>';
            $r[1] .= '</tr><tr><td style="font:bold 14px/16px Arial,Helvetica,sans-serif;color:#363636;padding:0 0 7px">';
            $r[1] .= htmlspecialchars_decode($mail['sitename']).'</td>';
            $r[1] .= '</tr></tbody></table></div></td></tr><tr>';
            $r[1] .= '<td bgcolor="#e0e2e5" style="height:1px;width:100%;line-height:1px;font-size:0">&nbsp;</td>';
            $r[1] .= '</tr><tr>';
            $r[1] .= '<td bgcolor="#e0e2e4" style="height:1px;width:100%;line-height:1px;font-size:0">&nbsp;</td>';
            $r[1] .= '</tr><tr>';
            $r[1] .= '<td bgcolor="#e8ebed" style="height:1px;width:100%;line-height:1px;font-size:0">&nbsp;</td>';
            $r[1] .= '</tr><tr>';
            $r[1] .= '<td bgcolor="#f1f3f6" style="height:1px;width:100%;line-height:1px;font-size:0">&nbsp;</td>';
            $r[1] .= '</tr></tbody></table></td>';
            $r[1] .= '<td bgcolor="#edeef1" style="width:1px;font-size:1px">&nbsp;</td>';
            $r[1] .= '<td bgcolor="#f0f2f3" style="width:1px;font-size:1px">&nbsp;</td>';
            $r[1] .= '<td bgcolor="#f5f6f7" style="width:1px;font-size:1px">&nbsp;</td>';
            $r[1] .= '<td bgcolor="#fafbfc" style="width:7px;font-size:1px">&nbsp;</td>';
            $r[1] .= '</tr></tbody></table></td></tr><tr>';
            $r[1] .= '<td align="center" style="padding-top:30px;padding-bottom:40px">';
            $r[1] .= '<table border="0" cellpadding="0" cellspacing="0" style="font-family:'."'Open+Sans','Open Sans'".',Helvetica,Arial,sans-serif;font-size:12px;line-height:18px;text-align:center;width:auto">';
            $r[1] .= '<tbody><tr><td style="color:#b7bdc1"><p style="Margin:0">';
            $r[1] .= htmlspecialchars_decode($mail['footer']);
            $r[1] .= '</p></td></tr></tbody></table></td></tr></tbody></table></div>';
            $r[1] .= '<div style="width:100%">';
            $r[1] .= '<table cellpadding="0" cellspacing="0" border="0" style="width:100%">';
            $r[1] .= '<tbody><tr><td align="center" bgcolor="#7d97ad" style="padding:10px 0">';
            $r[1] .= '<table border="0" cellpadding="0" cellspacing="0" style="font-family:'."'Open+Sans','Open Sans'".',Helvetica,Arial,sans-serif;font-size:14px;line-height:19px;text-align:center;width:auto">';
            $r[1] .= '<tbody><tr></tr></tbody></table></td>';
            $r[1] .= '</tr></tbody></table></div></center></td></tr></tbody>';
            $r[1] .= '</table></div><br></div></div></div></div></div>';
        }
    }
    return $r;
}
?>